user:
  outputs:
    default:
      account: sfedu02-pyb74658
      auth_type: password
      client_session_keep_alive: true
      connect_retries: 3
      connect_timeout: 30
      database: boa_db
      password: eyJraWQiOiI3NTY3NzYyNDQwNDQxODc4IiwiYWxnIjoiRVMyNTYifQ.eyJwIjoiNDUxMDczOTcyOjExNTQ3NDg5MTQzNyIsImlzcyI6IlNGOjEwNDkiLCJleHAiOjE4MDIyOTQ1Nzl9.07n4SnFyyR6Fl-HGRn59-dESLDWXGywD3GrVCxq4K8UvvswsyJRaJw3tQoPSxpECi96sLPWwDKcjf36vBxgmfw
      retry_on_database_errors: true
      role: boa_role
      schema: dbt_jbutikofer
      threads: 6
      type: snowflake
      user: boa
      warehouse: boa_wh
  target: default
